### ISSUE TITLE
`npm ERR! extraneous: progress@0.0.3`

### ISSUE THREAD

**Issue by garnold** [andrewchilds/overcast#37]
Not sure if this is really an issue, but NPM is reporting the following issue when running `npm list`:

```
$ sudo npm list --global
/usr/local/lib
...
└─┬ overcast@0.6.12
  ├─┬ aws-sdk@2.0.0-rc.14
  │ ├── aws-sdk-apis@2.0.13
  │ ├─┬ xml2js@0.2.4
  │ │ └── sax@0.6.1
  │ └── xmlbuilder@0.4.2
  ├── bluebird@1.2.1
  ├── colors@0.6.2
  ├─┬ linode-api@0.1.2
  │ ├─┬ optimist@0.2.8
  │ │ └── wordwrap@0.0.2
  │ ├── progress@0.0.3 extraneous
  │ └── request@1.9.9
  ├── lodash@2.4.1
  ├── minimist@0.0.8
  ├── rimraf@2.2.8
  └── slack-notify@0.1.1

npm ERR! extraneous: progress@0.0.3 /usr/local/lib/node_modules/overcast/node_modules/linode-api/node_modules/progress
```

**Comment by andrewchilds** [comment]
My best guess is that the `progress` module was in @fictorial's local `linode-api` repo when he ran `npm publish`, because it isn't referenced anywhere in the repo itself.

Since I'm bundling `node_modules`, I'll probably delete/rename the `dependencies` property in `package.json` so that npm doesn't install dependencies over the bundled versions. That should resolve this issue.
